client_config_backend: settings
client_config:
  client_id: 491460359726-lj3ilu22ir8ckqnjefot5gs99vmig1d2.apps.googleusercontent.com
  client_secret: JLABePXVFnVaNx_Lqzbu5b5Q
save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json
get_refresh_token: True
oauth_scope:
  - https://www.googleapis.com/auth/drive.file